let role=localStorage.getItem("safe_role")||"Jason";
let buyTab="all", currentPos=null, currentArea=null;
const boughtKey="japango_bought_v9";
const spentKey="japango_spent_v9";
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function go(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}
function openLink(url){location.href=url}
function getBought(){return JSON.parse(localStorage.getItem(boughtKey)||"[]")}
function toggleBought(name){let b=getBought();b=b.includes(name)?b.filter(x=>x!==name):[...b,name];localStorage.setItem(boughtKey,JSON.stringify(b));renderAll()}
function setRole(r){role=r;localStorage.setItem("safe_role",r);renderAll()}
function setBuyTab(t,el){buyTab=t;document.querySelectorAll("#mustbuy .tab").forEach(x=>x.classList.remove("active"));el.classList.add("active");renderMustBuy()}
function todayDay(){const t=new Date().toISOString().slice(0,10);return DATA.days.find(d=>d.date===t)||DATA.days[0]}
function hav(a,b,c,d){const R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180;const z=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function distValue(i){if(!currentPos||!i||i.lat==null||i.lng==null)return null;return hav(currentPos.lat,currentPos.lng,Number(i.lat),Number(i.lng))}
function distText(i){const km=distValue(i);if(km==null)return "";return km<1?Math.round(km*1000)+"m":km.toFixed(1)+"km"}
function walkText(i){const km=distValue(i);if(km==null)return "";return `步行約${Math.max(1,Math.round(km/4.5*60))}分鐘`}
function distBadge(i){const d=distText(i);return d?`<span class="pill">距離 ${d}</span><span class="pill">${walkText(i)}</span>`:""}
function nearestArea(){if(!currentPos)return null;return DATA.areas.map(a=>({...a,_dist:hav(currentPos.lat,currentPos.lng,a.lat,a.lng)})).sort((a,b)=>a._dist-b._dist)[0]}
function clearOldCache(){if("serviceWorker" in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister()))}if(window.caches){caches.keys().then(ns=>ns.forEach(n=>caches.delete(n)))}alert("已清除舊快取，請重新整理。")}
function locateMe(){if(!navigator.geolocation){alert("此瀏覽器不支援定位");return}const s=document.getElementById("gpsStatus");if(s)s.textContent="定位中...";navigator.geolocation.getCurrentPosition(p=>{currentPos={lat:p.coords.latitude,lng:p.coords.longitude};currentArea=nearestArea();if(s)s.textContent=`已定位：目前推定接近「${currentArea.name}」`;renderAll();go("ai")},e=>{if(s)s.textContent="定位失敗："+e.message;alert("定位未授權或失敗："+e.message)},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function useDemoArea(name){currentArea=DATA.areas.find(a=>a.name===name);currentPos={lat:currentArea.lat,lng:currentArea.lng};document.getElementById("gpsStatus").textContent=`Demo：目前推定接近「${currentArea.name}」`;renderAll();go("ai")}
function routeMatch(dest){const from=currentArea?.name;if(!from)return null;if(from===dest.area)return {title:`${from} → ${dest.name}`,options:[{label:"步行",best:true,mode:"🚶 Walk",time:walkText(dest)||"約5～15分鐘",fare:"¥0",stops:"近距離",transfer:"0次",steps:[`目前接近 ${from}`,`直接步行前往 ${dest.name}`,dest.note||""].filter(Boolean)}]};return DATA.routes.find(r=>r.from===from&&r.to===dest.area)}
function optionHtml(o){return `<div class="option ${o.best?'best':''}"><h4>${o.best?'⭐ ':''}${esc(o.label)}</h4><span class="pill">${esc(o.mode)}</span><span class="pill">時間：${esc(o.time)}</span><span class="pill">票價：${esc(o.fare)}</span><span class="pill">站數：${esc(o.stops)}</span><span class="pill">轉乘：${esc(o.transfer)}</span>${(o.steps||[]).map(s=>`<div class="step">${esc(s)}</div>`).join("")}</div>`}
function routeCard(dest){const r=routeMatch(dest);if(!r)return `<div class="card"><img class="photo" src="${img(dest.name)}"><span class="pill">${esc(dest.type)}</span><h3>${esc(dest.name)}</h3>${distBadge(dest)}<div class="warn">這段尚未內建多方案，請用 Google 即時路線。</div><div class="btns"><button class="btn map" onclick="openLink('${gdir(currentArea?.name||'現在位置',dest.q)}')">Google 即時路線</button><button class="btn apple" onclick="openLink('${amap(dest.q)}')">Apple</button></div></div>`;
return `<div class="card"><img class="photo" src="${img(dest.name)}"><span class="pill">${esc(dest.type)}</span><span class="pill">目的地：${esc(dest.area)}</span><h3>${esc(dest.name)}</h3>${distBadge(dest)}${dest.note?`<p>${esc(dest.note)}</p>`:""}<div class="aiHero"><b>${esc(r.title||dest.name)}</b><br><span class="small">參考票價，現場以 Google / 車站為準。</span></div>${r.options.map(optionHtml).join("")}<div class="btns"><button class="btn map" onclick="openLink('${gdir(currentArea?.name||'現在位置',dest.q)}')">Google 即時路線</button><button class="btn apple" onclick="openLink('${amap(dest.q)}')">Apple</button></div></div>`}
function recCard(r){const bought=getBought().includes(r.name);return `<div class="card"><img class="photo" src="${r.img}"><span class="pill">${esc(r.cat)}</span>${r.limited?'<span class="pill limited">🇯🇵 日本限定/日本較值得</span>':''}<span class="score">${r.score}分</span><h3>${esc(r.name)}</h3>${distBadge(r)}<p>${esc(r.why)}</p><span class="pill">價格：${esc(r.price)}</span><span class="pill">買：${esc(r.place)}</span><p class="small"><b>買不買：</b>${esc(r.save)}</p><div class="btns"><button class="btn ${bought?'ghost':'pink'}" onclick="toggleBought('${String(r.name).replaceAll("'","\\'")}')">${bought?'已買':'加入已買'}</button><button class="btn map" onclick="openLink('${gmap(r.q||r.name)}')">Google</button></div></div>`}
function foodCard(f){return `<div class="card"><img class="photo" src="${f.img}"><span class="pill">${esc(f.cat)}</span><span class="score">${f.score}分</span><h3>${esc(f.name)}</h3>${distBadge(f)}<p>${esc(f.why)}</p><span class="pill">${esc(f.queue)}</span><span class="pill">建議：${esc(f.bestTime)}</span><span class="pill">預估：${esc(f.price)}</span><div class="btns"><button class="btn map" onclick="openLink('${gmap(f.q)}')">Google</button></div></div>`}
function mapButtons(d){return `<div class="btns">${(d.mapLinks||[]).map(m=>`<button class="btn ghost" onclick="openLink('${gmap(m.q)}')">${esc(m.label)} ${distText(m)?'｜'+distText(m):''}</button>`).join("")}</div>`}
function areaRecommendations(){if(!currentArea)return [];const bought=getBought();return DATA.recommendations.filter(r=>r.area.includes(currentArea.name)&&(r.role.includes(role)||r.role.includes("全家"))&&!bought.includes(r.name)).sort((a,b)=>(b.score||0)-(a.score||0))}
function areaFoods(){if(!currentArea)return [];return DATA.foods.filter(f=>f.area.includes(currentArea.name)).sort((a,b)=>b.score-a.score)}
function renderToday(){const d=todayDay();document.getElementById("rolePill").textContent="角色："+role;document.getElementById("todayBox").innerHTML=`<div class="card"><img class="photo" src="${d.photo}"><span class="pill">今天：${esc(d.label)}</span><span class="pill">${esc(d.city)}・${esc(d.area)}</span><h3>${esc(d.hotel.name)}</h3><p>${esc(d.next)}</p><ul>${d.plan.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><div class="btns"><button class="btn map" onclick="locateMe()">更新定位</button><button class="btn map" onclick="openLink('${gmap(d.center)}')">今日地圖</button></div><h3>今日地圖快捷</h3>${mapButtons(d)}</div>`}
function renderAI(){const box=document.getElementById("aiBox");const d=todayDay();if(!currentArea){box.innerHTML=`<div class="aiHero"><h3>先按「更新定位」或 Demo</h3><p>定位後會自動顯示目前附近最值得買、最值得吃，以及今天未完成提醒。</p></div>`;return}const recs=areaRecommendations();const foods=areaFoods();const bought=getBought();const todayRecs=DATA.recommendations.filter(r=>d.keys.some(k=>r.name.includes(k)||r.cat.includes(k)||r.place.includes(k)));const done=todayRecs.filter(r=>bought.includes(r.name)).length;const total=Math.max(todayRecs.length,1);box.innerHTML=`<div class="aiHero"><h3>📍目前推定：${esc(currentArea.name)}</h3><p>依照 ${esc(role)}、目前位置、已買清單，自動推薦附近值得順便買/吃。</p><div class="progress"><div class="bar" style="width:${Math.round(done/total*100)}%"></div></div><p class="small">今日相關購物完成率：${done}/${todayRecs.length}</p></div><h3>⭐ 附近必買</h3>${recs.length?recs.map(recCard).join(""):'<div class="empty">附近暫無未買推薦，或已買完。</div>'}<h3>🍜 附近必吃/休息</h3>${foods.length?foods.map(foodCard).join(""):'<div class="empty">附近暫無內建美食。</div>'}`}
function renderSmart(){const box=document.getElementById("smartBox");const d=todayDay();const todays=DATA.destinations.filter(x=>(x.day||[]).includes(d.day));if(!currentArea){box.innerHTML=`<div class="aiHero"><h3>先按「更新定位」</h3><p>定位後點目的地，會出現多路線、票價、幾站、時間。</p></div>${todays.map(routeCard).join("")}`;return}box.innerHTML=`<div class="aiHero"><h3>目前位置：${esc(currentArea.name)}</h3></div><h3>今天目的地</h3>${todays.map(routeCard).join("")}<h3>全部常用目的地</h3>${DATA.destinations.filter(x=>!todays.includes(x)).map(routeCard).join("")}`}
function renderDays(){document.getElementById("daysList").innerHTML=DATA.days.map(d=>`<div class="card"><img class="photo" src="${d.photo}"><span class="pill">Day ${d.day}</span><span class="pill">${esc(d.city)}・${esc(d.area)}</span><h3>${esc(d.label)}｜${esc(d.hotel.name)}</h3><ul>${d.plan.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><p><b>下一步：</b>${esc(d.next)}</p><div class="btns"><button class="btn map" onclick="openLink('${gmap(d.center)}')">今日 Google</button><button class="btn apple" onclick="openLink('${amap(d.center)}')">今日 Apple</button></div>${mapButtons(d)}</div>`).join("")}
function renderMustBuy(){let arr=DATA.recommendations.slice();const q=(document.getElementById("searchBox")?.value||"").toLowerCase();const bought=getBought();if(buyTab==="bought")arr=arr.filter(x=>bought.includes(x.name));else if(buyTab==="limited")arr=arr.filter(x=>x.limited);else if(buyTab!=="all")arr=arr.filter(x=>x.role.includes(buyTab));if(q)arr=arr.filter(x=>(x.name+x.cat+x.place+x.why).toLowerCase().includes(q));arr=arr.sort((a,b)=>b.score-a.score);document.getElementById("mustBuyList").innerHTML=arr.map(recCard).join("")}
function renderFood(){document.getElementById("foodList").innerHTML=DATA.foods.map(foodCard).join("")}
function renderBudget(){const bought=getBought();let est=bought.length*2500;document.getElementById("budgetBox").innerHTML=`<div class="card"><h3>目前已買 ${bought.length} 項</h3><p>簡易估算：¥${est.toLocaleString()}（可之後升級成每項手動輸入金額）</p><ul>${bought.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><button class="btn red" onclick="localStorage.removeItem('${boughtKey}');renderAll()">清空已買</button></div>`}
function renderAll(){renderToday();renderAI();renderSmart();renderDays();renderMustBuy();renderFood();renderBudget()}
renderAll();
