let role=localStorage.getItem("safe_role")||"Jason";
let shopTab="all", currentPos=null, currentArea=null;
const boughtKey="safe_bought_smart";
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function go(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}
function openLink(url){location.href=url}
function getBought(){return JSON.parse(localStorage.getItem(boughtKey)||"[]")}
function toggleBought(name){let b=getBought();b=b.includes(name)?b.filter(x=>x!==name):[...b,name];localStorage.setItem(boughtKey,JSON.stringify(b));renderAll()}
function setRole(r){role=r;localStorage.setItem("safe_role",r);renderAll()}
function setShopTab(t,el){shopTab=t;document.querySelectorAll("#shopping .tab").forEach(x=>x.classList.remove("active"));el.classList.add("active");renderProducts()}
function todayDay(){const t=new Date().toISOString().slice(0,10);return DATA.days.find(d=>d.date===t)||DATA.days[0]}
function hav(a,b,c,d){const R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180;const z=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function distValue(i){if(!currentPos||!i||i.lat==null||i.lng==null)return null;return hav(currentPos.lat,currentPos.lng,Number(i.lat),Number(i.lng))}
function distText(i){const km=distValue(i);if(km==null)return "";return km<1?Math.round(km*1000)+"m":km.toFixed(1)+"km"}
function walkText(i){const km=distValue(i);if(km==null)return "";return `步行約${Math.max(1,Math.round(km/4.5*60))}分鐘`}
function distBadge(i){const d=distText(i);return d?`<span class="pill">距離 ${d}</span><span class="pill">${walkText(i)}</span>`:""}
function nearestArea(){if(!currentPos)return null;return DATA.areas.map(a=>({...a,_dist:hav(currentPos.lat,currentPos.lng,a.lat,a.lng)})).sort((a,b)=>a._dist-b._dist)[0]}
function clearOldCache(){if("serviceWorker" in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister()))}if(window.caches){caches.keys().then(ns=>ns.forEach(n=>caches.delete(n)))}alert("已清除舊快取，請重新整理。")}
function locateMe(){if(!navigator.geolocation){alert("此瀏覽器不支援定位");return}const s=document.getElementById("gpsStatus");if(s)s.textContent="定位中...";navigator.geolocation.getCurrentPosition(p=>{currentPos={lat:p.coords.latitude,lng:p.coords.longitude};currentArea=nearestArea();if(s)s.textContent=`已定位：你目前比較接近「${currentArea.name}」`;renderAll();go("smart")},e=>{if(s)s.textContent="定位失敗："+e.message;alert("定位未授權或失敗："+e.message)},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function routeFor(dest){const from=currentArea?.name;if(!from)return null;if(from===dest.area){return {method:"🚶 建議步行",time:walkText(dest)||"約5～15分鐘",fare:"¥0",steps:[`你目前接近 ${from}`,`直接步行前往 ${dest.name}`,dest.note||""].filter(Boolean),tip:"距離近，不需要搭車。"}}return DATA.routes.find(r=>r.from===from&&r.to===dest.area)}
function routeCard(dest){const r=routeFor(dest);if(!r){return `<div class="card"><img class="photo" src="${img(dest.name)}"><span class="pill">${esc(dest.type)}</span><h3>${esc(dest.name)}</h3>${distBadge(dest)}<p>${esc(dest.note||"")}</p><div class="empty"><b>這段尚未內建精準票價。</b><br>請用 Google Maps 即時導航。</div><div class="btns"><button class="btn map" onclick="openLink('${dir(currentArea?.name||'現在位置',dest.q)}')">Google 即時路線</button><button class="btn apple" onclick="openLink('${amap(dest.q)}')">Apple Maps</button></div></div>`}
return `<div class="card"><img class="photo" src="${img(dest.name)}"><span class="pill">${esc(dest.type)}</span><span class="pill">目的地：${esc(dest.area)}</span><h3>${esc(dest.name)}</h3>${distBadge(dest)}<div class="route"><h3 style="margin:0 0 8px">${esc(r.method)}</h3><span class="pill">總時間：${esc(r.time)}</span><span class="pill">車資：${esc(r.fare)}</span>${r.steps.map(x=>`<div class="routeStep">${esc(x)}</div>`).join("")}<p class="small"><b>提醒：</b>${esc(r.tip||"")}</p></div><div class="btns"><button class="btn map" onclick="openLink('${dir(currentArea?.name||'現在位置',dest.q)}')">Google 即時路線</button><button class="btn apple" onclick="openLink('${amap(dest.q)}')">Apple Maps</button></div></div>`}
function productCard(p){const bought=getBought().includes(p.name);return `<div class="card"><img class="photo" src="${p.img}"><span class="pill">${esc(p.cat)}</span><span class="pill">${esc(p.tier)}</span><span class="score">${esc(p.score)}分</span><h3>${esc(p.name)}</h3>${distBadge(p)}<p>${esc(p.why)}</p><span class="pill">買：${esc(p.where)}</span><span class="pill">預估：${esc(p.price||"依現場")}</span><div class="btns"><button class="btn ${bought?'ghost':'pink'}" onclick="toggleBought('${String(p.name).replaceAll("'","\\'")}')">${bought?'已買':'加入已買'}</button><button class="btn map" onclick="openLink('${gmap(p.q||p.name)}')">Google</button></div></div>`}
function foodCard(f){return `<div class="card"><img class="photo" src="${f.img}"><span class="pill">${esc(f.city)}・${esc(f.area)}</span><span class="score">${esc(f.score)}分</span><h3>${esc(f.name)}</h3>${distBadge(f)}<p>${esc(f.desc)}</p><span class="pill">${esc(f.queueText||"🟡 普通")}</span><span class="pill">建議：${esc(f.bestTime||"避開尖峰")}</span><span class="pill">預估：${esc(f.price)}</span><div class="btns"><button class="btn map" onclick="openLink('${gmap(f.q)}')">Google</button></div></div>`}
function mapButtons(d){return `<div class="btns">${(d.mapLinks||[]).map(m=>`<button class="btn ghost" onclick="openLink('${gmap(m.q)}')">${esc(m.label)} ${distText(m)?'｜'+distText(m):''}</button>`).join("")}</div>`}
function renderToday(){const d=todayDay();document.getElementById("rolePill").textContent="角色："+role;document.getElementById("todayBox").innerHTML=`<div class="card"><img class="photo" src="${d.photo}"><span class="pill">今天：${esc(d.label)}</span><span class="pill">${esc(d.city)}・${esc(d.area)}</span><h3>${esc(d.hotel.name)}</h3><p>${esc(d.next)}</p><ul>${d.plan.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><div class="btns"><button class="btn map" onclick="locateMe()">更新定位</button><button class="btn map" onclick="openLink('${gmap(d.center)}')">今日地圖</button></div><h3>今日地圖快捷</h3>${mapButtons(d)}</div>`}
function renderSmart(){const box=document.getElementById("smartBox");const d=todayDay();const todays=DATA.destinations.filter(x=>(x.day||[]).includes(d.day));const all=DATA.destinations;if(!currentArea){box.innerHTML=`<div class="smartHero"><h3>先按「更新定位」</h3><p>定位後會顯示你目前接近的區域，然後點任何目的地，就會出現推薦交通、站名、時間、票價。</p><button class="btn map" onclick="locateMe()">更新定位</button></div><h3>今天可點的目的地</h3>${todays.map(x=>routeCard(x)).join("")}`;return}box.innerHTML=`<div class="smartHero"><h3>📍目前推定位置：${esc(currentArea.name)}</h3><p>下面目的地點開後，會自動套用「${esc(currentArea.name)} → 目的地」的內建交通路線。</p></div><h3>今天目的地</h3>${todays.map(x=>routeCard(x)).join("")}<h3>全部常用目的地</h3>${all.filter(x=>!todays.includes(x)).map(x=>routeCard(x)).join("")}`}
function renderDays(){document.getElementById("daysList").innerHTML=DATA.days.map(d=>`<div class="card"><img class="photo" src="${d.photo}"><span class="pill">Day ${d.day}</span><span class="pill">${esc(d.city)}・${esc(d.area)}</span><h3>${esc(d.label)}｜${esc(d.hotel.name)}</h3><ul>${d.plan.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><p><b>下一步：</b>${esc(d.next)}</p><div class="btns"><button class="btn map" onclick="openLink('${gmap(d.center)}')">今日 Google</button><button class="btn apple" onclick="openLink('${amap(d.center)}')">今日 Apple</button></div><h3>地圖快捷</h3>${mapButtons(d)}</div>`).join("")}
function renderProducts(){let arr=DATA.products.slice();const bought=getBought();if(shopTab==="bought")arr=arr.filter(p=>bought.includes(p.name));else if(shopTab!=="all")arr=arr.filter(p=>(p.role||[]).includes(shopTab));document.getElementById("productList").innerHTML=arr.map(productCard).join("")}
function renderFood(){document.getElementById("foodList").innerHTML=DATA.foods.map(foodCard).join("")}
function renderPlaces(){document.getElementById("placeList").innerHTML=DATA.destinations.map(routeCard).join("")}
function renderAll(){renderToday();renderSmart();renderDays();renderProducts();renderFood();renderPlaces()}
renderAll();
